---
- name: Install nginx (apt)
  when: package_manager == "apt"
  block:
    - name: Apt update
      ansible.builtin.apt:
        update_cache: true
      become: true

    - name: Install nginx
      ansible.builtin.apt:
        name: nginx
        state: present
      become: true

- name: Install nginx (dnf)
  when: package_manager == "dnf"
  block:
    - name: Install nginx
      ansible.builtin.dnf:
        name: nginx
        state: present
      become: true
