---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Generate main.tf
      ansible.builtin.template:
        src: main.tf.j2
        dest: main.tf
        lstrip_blocks: true

    - name: Terraform destroy
      community.general.terraform:
        project_path: "./"
        state: absent
